### ISSUE TITLE
Leak in icalrecurrencetype_from_string

### ISSUE THREAD

**Issue by winterz** [libical/libical#254]
when running icalrecur_test -r there is a small memory leak
```
==5037==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 294 byte(s) in 33 object(s) allocated from:
    #0 0x459dd0 in strdup /usr/local/src/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:562
    #1 0x7f30f5a797f4 in icalmemory_strdup /home/allen/projects/libical/libical/src/libical/icalmemory.c:241:12
    #2 0x7f30f5a88ab0 in icalrecurrencetype_from_string /home/allen/projects/libical/libical/src/libical/icalrecur.c:588:32
    #3 0x504f91 in main /home/allen/projects/libical/libical/src/test/icalrecur_test.c:480:17
    #4 0x7f30f4d3a57f in __libc_start_main (/lib64/libc.so.6+0x2057f)

SUMMARY: AddressSanitizer: 294 byte(s) leaked in 33 allocation(s).
```

**Comment by ksmurchison** [comment]
https://github.com/libical/libical/commit/92f43d362aefe56f6a7144046e1c4f10f6c83720
