### ISSUE TITLE
Crash in icaltimezone_get_tznames_from_vtimezone when parsing a pathologic ICS file

### ISSUE THREAD

**Issue by muelli** [libical/libical#263]
With afl I found the following crash:
```

>env env ASAN_OPTIONS=abort_on_error=1 gdb -ex "set pagination 0" -ex "r" -ex "t a a bt full" --args src/test/parser /tmp/crash.ics 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from src/test/parser...done.
Starting program: /home/muelli/vcs/libical/build/src/test/parser /tmp/crash.ics
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/home/muelli/vcs/libical/src/libical/icalarray.c:193:9: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/x86_64-linux-gnu/bits/string3.h:53:10: runtime error: null pointer passed as argument 2, which is declared to never be null

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6eb105a in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2

Thread 1 (Thread 0x7ffff7fc67c0 (LWP 15019)):
#0  0x00007ffff6eb105a in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#1  0x00007ffff68fec1f in icaltimezone_get_tznames_from_vtimezone (component=component@entry=0x60700000ab30) at /home/muelli/vcs/libical/src/libical/icaltimezone.c:398
        __s2_len = 13
        comp = 0x0
        type = <optimised out>
        prop = <optimised out>
        current_tzname = <optimised out>
        standard_tzname = 0x3000007cd ""
        daylight_tzname = 0x6020000081d0 "EDT"
#2  0x00007ffff690fb19 in icaltimezone_get_vtimezone_properties (component=0x60700000ab30, zone=0x7fffffffd3f0) at /home/muelli/vcs/libical/src/libical/icaltimezone.c:285
        prop = <optimised out>
        tzid = <optimised out>
#3  icaltimezone_array_append_from_vtimezone (timezones=0x60400000b790, child=child@entry=0x60700000ab30) at /home/muelli/vcs/libical/src/libical/icaltimezone.c:1237
No locals.
#4  0x00007ffff68730df in icalcomponent_add_component (parent=0x60700000c650, child=0x60700000ab30) at /home/muelli/vcs/libical/src/libical/icalcomponent.c:480
        child = 0x60700000ab30
        parent = 0x60700000c650
#5  0x00007ffff68a10d1 in icalparser_add_line (parser=parser@entry=0x60d00000cf70, line=line@entry=0x60700000a200 "END:VTIMEZONE") at /home/muelli/vcs/libical/src/libical/icalparser.c:744
        tail = <optimised out>
        str = 0x602000008150 "VTIMEZONE"
        vcount = 0
        prop = <optimised out>
        prop_kind = <optimised out>
        value = <optimised out>
        value_kind = ICAL_NO_VALUE
        __PRETTY_FUNCTION__ = "icalparser_add_line"
#6  0x0000000000401183 in main (argc=<optimised out>, argv=<optimised out>) at /home/muelli/vcs/libical/src/test/icaltestparser.c:104
        line = 0x60700000a200 "END:VTIMEZONE"
        stream = 0x61600000fc80
        c = <optimised out>
        parser = 0x60d00000cf70
(gdb) up
#1  0x00007ffff68fec1f in icaltimezone_get_tznames_from_vtimezone 
(component=component@entry=0x60700000ab30) at /home/muelli/vcs/libical/src/libical/icaltimezone.c:398
398	    if (standard_tzname && !strcmp(standard_tzname, "Standard Time"))
(gdb) l
393	        comp = icalcomponent_get_next_component(component, ICAL_ANY_COMPONENT);
394	    }
395	
396	    /* Outlook (2000) places "Standard Time" and "Daylight Time" in the TZNAME
397	       strings, which is totally useless. So we return NULL in that case. */
398	    if (standard_tzname && !strcmp(standard_tzname, "Standard Time"))
399	        return NULL;
400	
401	    /* If both standard and daylight TZNAMEs were found, if they are the same
402	       we return just one, else we format them like "EST/EDT". */
(gdb) p standard_tzname 
$1 = 0x3000007cd ""
(gdb) 

```

[crash.ics.gz](https://github.com/libical/libical/files/649370/crash.ics.gz)

**Comment by ksmurchison** [comment]
I'm not seeing why this is crashing.  If standard_tzname is non-NULL, strcmp() should be happy.  Unless the string itself isn't terminated properly.

**Comment by muelli** [comment]
I think standard_tzname pointed to a random memory location, i.e. not allocated.  Can you reproduce with the file provided?

**Comment by ksmurchison** [comment]
How were you ingesting the resources in the file?

**Comment by muelli** [comment]
I don't understand your question. `src/test/parser /tmp/crash.ics` is how I can make it crash.

**Comment by ksmurchison** [comment]
OK.  That answers my question.

**Comment by ksmurchison** [comment]
This should be fixed with https://github.com/libical/libical/commit/53e68ff6e2133c54ff44df53e8b75ef21125fb3d

The problem was that the parser allowed any valid value type to be parsed, regardless of whether it was legal for the given property, and the code accessing the property value was assuming the default type.
