### ISSUE TITLE
icalparser_add_line: attempting free on address which was not malloc()-ed: 0x607000009e4f

### ISSUE THREAD

**Issue by muelli** [libical/libical#278]
afl found an input which upsets ASan:
```
==21370==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x607000009e4f in thread T0
    #0 0x7ffff6f022ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
    #1 0x7ffff68a1cc0 in icalparser_add_line /home/muelli/vcs/libical/src/libical/icalparser.c:1001
    #2 0x4011ba in main /home/muelli/vcs/libical/src/test/icaltestparser.c:104
    #3 0x7ffff56b082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x4013b8 in _start (/home/muelli/vcs/libical/build/src/test/parser+0x4013b8)

0x607000009e4f is located 63 bytes inside of 65-byte region [0x607000009e10,0x607000009e51)
allocated by thread T0 here:
    #0 0x7ffff6f0279a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7ffff688ad65 in icalmemory_new_buffer /home/muelli/vcs/libical/src/libical/icalmemory.c:251
    #2 0x61200000a9bf  (<unknown module>)

SUMMARY: AddressSanitizer: bad-free ??:0 __interceptor_free
==21370==ABORTING

Program received signal SIGABRT, Aborted.
0x00007ffff56c5428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Thread 1 (Thread 0x7ffff7fc47c0 (LWP 21370)):
#0  0x00007ffff56c5428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 21370
        selftid = 21370
#1  0x00007ffff56c702a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 140737488339248, 10372548445935199232, 85, 1, 140737353894624, 1, 1, 60, 0, 140737336399534, 18, 0, 140737488338736, 1, 18}}, sa_flags = -151978013, sa_restorer = 0x7fffffffc220}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff6f17dc9 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#3  0x00007ffff6f0a769 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#4  0x00007ffff6f0f5d2 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#5  0x00007ffff6f0a019 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#6  0x00007ffff6f0873f in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#7  0x00007ffff6e8b618 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#8  0x00007ffff6f0229e in free () from /usr/lib/x86_64-linux-gnu/libasan.so.2
No symbol table info available.
#9  0x00007ffff68a1cc1 in icalparser_add_line (parser=parser@entry=0x60d00000cf70, line=line@entry=0x61200000a9c0 "X;TZID=America/Los\202Angeles:-UMEVENTS: 10\034ENDs_AngelesDELEGATED-FROM=\"\";[ENT-BY=\"//\"?CN=\"b\";DM\277=\"//\";LANGUAGE=\"b\"://") at /home/muelli/vcs/libical/src/libical/icalparser.c:1001
        param = 0x604000009650
        kind = <optimised out>
        tail = 0x60700000a270
        name_heap = 0x0
        name = <optimised out>
        pvalue = 0x607000009e4f "\""
        str = 0x607000009e10 "=America/Los\202Angeles:-UMEVENTS: 10\034ENDs_AngelesDELEGATED-FROM=\"\""
        vcount = 0
        prop = 0x60600000b6c0
        prop_kind = ICAL_X_PROPERTY
        value = <optimised out>
        value_kind = <optimised out>
        __PRETTY_FUNCTION__ = "icalparser_add_line"
#10 0x00000000004011bb in main (argc=<optimised out>, argv=<optimised out>) at /home/muelli/vcs/libical/src/test/icaltestparser.c:104
        line = 0x61200000a9c0 "X;TZID=America/Los\202Angeles:-UMEVENTS: 10\034ENDs_AngelesDELEGATED-FROM=\"\";[ENT-BY=\"//\"?CN=\"b\";DM\277=\"//\";LANGUAGE=\"b\"://"
        stream = 0x61600000fc80
        c = <optimised out>
        parser = 0x60d00000cf70
A debugging session is active.
```

This the `test/parser` run against the [attached file](https://github.com/libical/libical/files/665836/malloc.ical.gz). 

This might be Coverity ID 154924

**Comment by ksmurchison** [comment]
Fixed with commit https://github.com/libical/libical/commit/4433081ef4e946c4ff5cf58cde13adc3f40d1afb
