### ISSUE TITLE
FTBFS with -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address"

### ISSUE THREAD

**Issue by mejo-** [libical/libical#292]
When trying to build libical git master (29cd90c21b487b5b4335059ed1a8bf7e5822a170) with -fsanitize=address, it fails to build from source. This doesn't happen with tag 2.0.0 and was introduced somewhere with the merge of branch 'glib' (b061071cc976e925cdea85c8020d5a17c1f3b693).

```
$ cmake -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DSTATIC_ONLY=true -DCMAKE_CXX_COMPILER="clang++-3.9"
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is Clang 3.9.1
[...]
$ make
[...]
Scanning dependencies of target icalvcal-static
[ 50%] Building C object src/libicalvcal/CMakeFiles/icalvcal-static.dir/icalvcal.c.o
[ 51%] Building C object src/libicalvcal/CMakeFiles/icalvcal-static.dir/vobject.c.o
[ 51%] Building C object src/libicalvcal/CMakeFiles/icalvcal-static.dir/vcaltmp.c.o
[ 51%] Building C object src/libicalvcal/CMakeFiles/icalvcal-static.dir/vcc.c.o
[ 52%] Linking C static library ../../lib/libicalvcal.a
[ 52%] Built target icalvcal-static
Scanning dependencies of target src-generator
[ 52%] Building C object src/libical-glib/CMakeFiles/src-generator.dir/tools/generator.c.o
[ 53%] Building C object src/libical-glib/CMakeFiles/src-generator.dir/tools/xml-parser.c.o
[ 53%] Linking C executable ../../bin/src-generator
[ 53%] Built target src-generator
[ 54%] Generating i-cal-array.h, i-cal-array.c, i-cal-attach.h, i-cal-attach.c, i-cal-comp-iter.h, i-cal-comp-iter.c, i-cal-component.h, i-cal-component.c, i-cal-datetimeperiod-type.h, i-cal-datetimeperiod-type.c, i-cal-derived-parameter.h, i-cal-derived-parameter.c, i-cal-derived-property.h, i-cal-derived-property.c, i-cal-derived-value.h, i-cal-derived-value.c, i-cal-duration-type.h, i-cal-duration-type.c, i-cal-enums.h, i-cal-enums.c, i-cal-error.h, i-cal-error.c, i-cal-geo-type.h, i-cal-geo-type.c, i-cal-langbind.h, i-cal-langbind.c, i-cal-memory.h, i-cal-memory.c, i-cal-mime.h, i-cal-mime.c, i-cal-parameter.h, i-cal-parameter.c, i-cal-parser.h, i-cal-parser.c, i-cal-period-type.h, i-cal-period-type.c, i-cal-property.h, i-cal-property.c, i-cal-recur-iterator.h, i-cal-recur-iterator.c, i-cal-recurrence-type.h, i-cal-recurrence-type.c, i-cal-recur.h, i-cal-recur.c, i-cal-reqstat-type.h, i-cal-reqstat-type.c, i-cal-restriction.h, i-cal-restriction.c, i-cal-time-span.h, i-cal-time-span.c, i-cal-timetype.h, i-cal-timetype.c, i-cal-time.h, i-cal-time.c, i-cal-timezone-phase.h, i-cal-timezone-phase.c, i-cal-timezonetype.h, i-cal-timezonetype.c, i-cal-timezone.h, i-cal-timezone.c, i-cal-trigger-type.h, i-cal-trigger-type.c, i-cal-unknowntokenhandling.h, i-cal-unknowntokenhandling.c, i-cal-value.h, i-cal-value.c, libical-glib-private.h, i-cal-forward-declarations.h

=================================================================
==12246==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 264000 byte(s) in 66 object(s) allocated from:
    #0 0x7feaa4e41d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7feaa4868e08 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4fe08)
    #2 0x555cf6d7496d in generate_library (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x896d)
    #3 0x555cf6d74e38 in main (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x8e38)
    #4 0x7feaa40e02b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 36177 byte(s) in 1020 object(s) allocated from:
    #0 0x7feaa4e41d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7feaa4868e08 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4fe08)

Direct leak of 11949 byte(s) in 837 object(s) allocated from:
    #0 0x7feaa4e41d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7feaa4868e08 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4fe08)
    #2 0x555cf6d71e4e in is_enum_type (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x5e4e)
    #3 0x555cf6d72594 in get_inline_parameter (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x6594)
    #4 0x555cf6d71d42 in get_source_method_code (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x5d42)
    #5 0x555cf6d72b6b in get_source_method_body (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x6b6b)
    #6 0x555cf6d70397 in generate_code_from_template (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x4397)
    #7 0x555cf6d712f4 in generate_source (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x52f4)
    #8 0x555cf6d73690 in generate_header_and_source (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x7690)
    #9 0x555cf6d7496d in generate_library (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x896d)
    #10 0x555cf6d74e38 in main (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x8e38)
    #11 0x7feaa40e02b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 11949 byte(s) in 837 object(s) allocated from:
    #0 0x7feaa4e41d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7feaa4868e08 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4fe08)
    #2 0x555cf6d71e4e in is_enum_type (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x5e4e)
    #3 0x555cf6d72609 in get_inline_parameter (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x6609)
    #4 0x555cf6d71d42 in get_source_method_code (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x5d42)
    #5 0x555cf6d72b6b in get_source_method_body (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x6b6b)
    #6 0x555cf6d70397 in generate_code_from_template (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x4397)
    #7 0x555cf6d712f4 in generate_source (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x52f4)
    #8 0x555cf6d73690 in generate_header_and_source (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x7690)
    #9 0x555cf6d7496d in generate_library (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x896d)
    #10 0x555cf6d74e38 in main (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x8e38)
    #11 0x7feaa40e02b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 4374 byte(s) in 304 object(s) allocated from:
    #0 0x7feaa4e41d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x7feaa4868e08 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4fe08)
    #2 0x555cf6d71e4e in is_enum_type (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x5e4e)
    #3 0x555cf6d72ced in get_source_method_body (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x6ced)
    #4 0x555cf6d70397 in generate_code_from_template (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x4397)
    #5 0x555cf6d712f4 in generate_source (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x52f4)
    #6 0x555cf6d73690 in generate_header_and_source (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x7690)
    #7 0x555cf6d7496d in generate_library (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x896d)
    #8 0x555cf6d74e38 in main (/home/user/devel/libical-git+29cd90c2/build/bin/src-generator+0x8e38)
    #9 0x7feaa40e02b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: 328449 byte(s) leaked in 3064 allocation(s).
src/libical-glib/CMakeFiles/ical-glib.dir/build.make:94: recipe for target 'src/libical-glib/i-cal-array.h' failed
make[2]: *** [src/libical-glib/i-cal-array.h] Error 1
make[2]: *** Deleting file 'src/libical-glib/i-cal-array.h'
CMakeFiles/Makefile2:788: recipe for target 'src/libical-glib/CMakeFiles/ical-glib.dir/all' failed
make[1]: *** [src/libical-glib/CMakeFiles/ical-glib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by mejo-** [comment]
I can verify that this is somewhere in the glib module. If I pass '-DICAL_GLIB=false' to cmake, then it doesn't FTBFS (fail to build from source):

`$ cmake -DICAL_GLIB=false -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DSTATIC_ONLY=true -DCMAKE_CXX_COMPILER="clang++-3.9"`

**Comment by winterz** [comment]
I already have that implemented.
All you need to do is pass -DADDRESS_SANITIZER=True to CMake
