### ISSUE TITLE
Crash in cleanVObject

### ISSUE THREAD

**Issue by winterz** [libical/libical#528]
as seen in https://bugs.kde.org/show_bug.cgi?id=446025
```
#6  0x00007f6b8aa05758 in cleanVObject (o=0x564633f031c0) at
/usr/src/debug/libical-3.0.11-1.fc35.x86_64/src/libicalvcal/vobject.c:591
#7  0x00007f6b8aa08e94 in finiLex () at
/usr/src/debug/libical-3.0.11-1.fc35.x86_64/src/libicalvcal/vcc.c:855
#8  Parse_MIMEHelper () at
/usr/src/debug/libical-3.0.11-1.fc35.x86_64/src/libicalvcal/vcc.c:1171
#9  0x00007f6b8aa09e96 in Parse_MIME_FromFile (file=file@entry=0x56463401aea0)
at /usr/src/debug/libical-3.0.11-1.fc35.x86_64/src/libicalvcal/vcc.c:1209
#10 0x00007f6b8aa09f11 in Parse_MIME_FromFileName (fname=0x564633f062f8
"/tmp/mozilla_paul0/cal.ics") at
/usr/src/debug/libical-3.0.11-1.fc35.x86_64/src/libicalvcal/vcc.c:1220
#11 0x00007f6b8dc101fb in KCalendarCore::VCalFormat::load (this=0x7ffd46eb2120,
calendar=..., fileName=...) at
/usr/src/debug/kf5-kcalendarcore-5.88.0-1.fc35.x86_64/src/vcalformat.cpp:92
#12 0x00007f6b8dbd33ea in KCalendarCore::FileStorage::load
(this=this@entry=0x7ffd46eb2230) at
/usr/src/debug/kf5-kcalendarcore-5.88.0-1.fc35.x86_64/src/filestorage.cpp:117
#13 0x00007f6b8b8dc8cd in Akonadi::ICalImporter::importIntoExistingResource
(this=this@entry=0x564633efbaf0, url=..., collection=...) at
/usr/src/debug/kf5-akonadi-calendar-21.04.3-1.fc35.x86_64/src/icalimporter.cpp:184
```

**Comment by winterz** [comment]
@mcrha I wonder if this is related to your recent changes in vcal?
I asked the OP if they could provide the calendar file that caused the crash.

**Comment by mcrha** [comment]
You are right, the line 855 had been added in:

https://github.com/libical/libical/commit/7a5f8ccf29967d314fb0aa70ffb03a267151287a#diff-f7ab9a81b9840acea99cf4faf7d89e526308c6f56baa1fdcabf2ca6420da8449

Having the file will help (it seems to be downloaded from the Internet). The files I've tried here do not exhibit the problem.

I also suspect the file is incomplete or otherwise broken, because with valid files the line 855 is not reached.

My test program:
```
/* gcc `pkg-config --cflags --libs libical` ical.c -g -O0 -o ical && ./ical */

#include <stdio.h>
#include <libical/vcc.h>

int main (int argc, char **argv)
{
	VObject *obj;

	if (argc != 2) {
		fprintf (stderr, "Requires one argument, file to parse\n");
		return 1;
	}

	obj = Parse_MIME_FromFileName(argv[1]);
	if (!obj) {
		fprintf (stderr, "Failed to parse '%s'\n", argv[1]);
		return 2;
	}

	printf ("Parsed object\n");
	cleanVObject (obj);

	return 0;
}
```

**Comment by winterz** [comment]
we fixed this as I recall.
closing
