### ISSUE TITLE
Error in zone.tab causes crash [sf#59]

### ISSUE THREAD

**Issue by winterz** [libical/libical#59]
When zone.tab contains an invalid line, the following crash trace is obtained when libical is used:

#6  0xb5fcee27 in ?? () from /usr/lib/libical.so.0
#7  0xbfffb138 in ?? ()
#8  0xbfffc42f in ?? ()
#9  0x00000005 in ?? ()
#10 0xb5fcf0b9 in icaltimezone_get_utc_timezone () from /usr/lib/libical.so.0
#11 0xb5fca4ac in icaltime_compare () from /usr/lib/libical.so.0
#12 0xb5fcd168 in ?? () from /usr/lib/libical.so.0
#13 0x00000777 in ?? ()
#14 0x00000003 in ?? ()
#15 0xb5fcd647 in ?? () from /usr/lib/libical.so.0
#16 0x08300858 in ?? ()
#17 0x00000059 in ?? ()
#18 0xb5fcd8fd in icaltimezone_array_append_from_vtimezone () from /usr/lib/libical.so.0
#19 0xb5fbe382 in icalcomponent_add_component () from /usr/lib/libical.so.0
#20 0xb5fc2f70 in icalparser_add_line () from /usr/lib/libical.so.0
#21 0xb5fc3974 in icalparser_parse () from /usr/lib/libical.so.0
#22 0xb5fc3b52 in icalparser_parse_string () from /usr/lib/libical.so.0
#23 0xb5fc061d in icalcomponent_new_from_string () from /usr/lib/libical.so.0

To reproduce this, first compile and run the attached program which corrupts zone.tab. The calendar file string which is being parsed is attached also.

**Comment by winterz** [comment]
closing ancient

**Comment by winterz** [comment]
I tested and what we get with modern libical is error messages "Invalid timezone description line" and "Invalid coordinate".

#367 is currently open if we want to continue investigating
