### ISSUE TITLE
Build fails with GOBJECT_INTROSPECTION on Mac with Apple Clang

### ISSUE THREAD

**Issue by winterz** [libical/libical#599]
On Mac with Apple Clang.

Using `cmake "-DCMAKE_BUILD_TYPE=Debug -DGOBJECT_INTROSPECTION=True -DUSE_BUILTIN_TZDATA=OFF -DICAL_GLIB_VAPI=ON"`

the compile fails like so:
```
[ 56%] Building C object src/libicalss/CMakeFiles/icalss.dir/icaldirset.c.o
In file included from /Users/allen/projects/libical/libical/build-testclang4glib-clang/src/libical/g-ir-cpp-a1eetv9n.c:4:
/Users/allen/projects/libical/libical/build-testclang4glib-clang/src/libical/ical.h:137:10: fatal error: 'time.h' file not found
#include <time.h>
         ^~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 179, in preprocess
    self.spawn(pp_args)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/gobject-introspection/1.74.0/bin/g-ir-scanner", line 99, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/Cellar/gobject-introspection/1.74.0/lib/gobject-introspection/giscanner/scannermain.py", line 600, in scanner_main
    ss, filenames = create_source_scanner(options, args)
  File "/usr/local/Cellar/gobject-introspection/1.74.0/lib/gobject-introspection/giscanner/scannermain.py", line 471, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/Cellar/gobject-introspection/1.74.0/lib/gobject-introspection/giscanner/sourcescanner.py", line 265, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.74.0/lib/gobject-introspection/giscanner/sourcescanner.py", line 311, in _parse
    cc.preprocess(tmp_name_cpp,
  File "/usr/local/Cellar/gobject-introspection/1.74.0/lib/gobject-introspection/giscanner/ccompiler.py", line 309, in preprocess
    self.compiler.preprocess(source=source,
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 181, in preprocess
    raise CompileError(msg)
distutils.errors.CompileError: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' failed with exit code 1
[ 57%] Building C object src/libicalvcal/CMakeFiles/icalvcal.dir/vcc.c.o
[ 57%] Building C object src/libical-glib/CMakeFiles/ical-glib-static.dir/i-cal-time-span.c.o
In file included from /Users/allen/projects/libical/libical/build-testclang4glib-clang/src/libical/g-ir-cpp-w7q3_gll.c:4:
/Users/allen/projects/libical/libical/build-testclang4glib-clang/src/libical/ical.h:137:10: fatal error: 'time.h' file not found
#include <time.h>
         ^~~~~~~~
1 error generated.
```

**Comment by winterz** [comment]
@tintou any thoughts about this? anything look familiar?

**Comment by winterz** [comment]
I can reproduce in the v3.0.14 tag so this isn't a regression for the upcoming 3.0.15 release.
not a blocker for 3.0.15.

**Comment by winterz** [comment]
this doesn't happen any longer. 
there are other issues related to VAPI and GOBJECT_INSPECTION that I'm fixing in other patches.
namely, not setting DYLD_LIBRARY_PATH
also we need some documentation on the required homebrew dependencies

**Comment by winterz** [comment]
seems ok now
