### ISSUE TITLE
Using VALA causes core dump (bus error)

### ISSUE THREAD

**Issue by winterz** [libical/libical#771]
No idea if this is a vala bug or a bug in how we're using it.

here's the bt (from Fedora 39)
```
#0  vala_markup_reader_space (self=<optimized out>) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valamarkupreader.c:1299
1299                            _tmp4_ = _tmp3_[0];
#0  vala_markup_reader_space (self=<optimized out>) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valamarkupreader.c:1299
#1  vala_markup_reader_space (self=self@entry=0x56219eb40910) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valamarkupreader.c:1282
#2  0x00007f8b197065d0 in vala_markup_reader_read_token (self=0x56219eb40910, token_begin=0x7ffd34792a60, token_end=0x7ffd34792a50) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valamarkupreader.c:562
#3  0x00007f8b196b3d54 in vala_gir_parser_next (self=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:1494
#4  0x00007f8b196c12cf in vala_gir_parser_parse_parameter (default_name=0x56219ebec430 "arg0", comment=<synthetic pointer>, scope=<synthetic pointer>, destroy_idx=<synthetic pointer>, closure_idx=<synthetic pointer>, array_length_idx=<synthetic pointer>, caller_allocates=<synthetic pointer>, self=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:6087
#5  vala_gir_parser_parse_function (self=0x56219eb3cc60, element_name=0x7f8b197b81ba "method") at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:9235
#6  0x00007f8b196bb94b in vala_gir_parser_parse_signal (self=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:9613
#7  vala_gir_parser_parse_class (self=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:7683
#8  vala_gir_parser_parse_namespace (self=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:4915
#9  vala_gir_parser_parse_repository (self=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:3690
#10 vala_gir_parser_parse_file (self=0x56219eb3cc60, source_file=<optimized out>) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:1474
#11 0x00007f8b19680d4a in vala_code_context_accept (visitor=0x56219eb3cc60, self=0x56219d034a10) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valacodecontext.c:2024
#12 vala_code_context_accept (self=0x56219d034a10, visitor=0x56219eb3cc60) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valacodecontext.c:1993
#13 0x00007f8b196b286b in vala_gir_parser_parse (self=<optimized out>, context=0x56219d034a10) at /usr/src/debug/vala-0.56.17-1.fc39.x86_64/vala/valagirparser.c:1012
```

**Comment by winterz** [comment]
@tintou   @mcrha   maybe you can give a hint?

**Comment by winterz** [comment]
I was hoping that the changes in #805 would fix this one.  
no joy

**Comment by tintou** [comment]
What is the version of your Vala compiler?

**Comment by winterz** [comment]
seems to be fixed now.  my bad.  
if the problems reappear I'll reopen and give more details.

**Comment by winterz** [comment]
in any event, vapigen shouldn't crash.  probably I need to report the backtrace upstream
