### ISSUE TITLE
libical testcase now fails to build on hppa and powerpc on Debian

### ISSUE THREAD

**Issue by babelouest** [libical/libical#852]
Hello, 

As the libical maintainer for Debian, a bug emerged in the last release: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1091461

Lately, Debian switched the `time_t` length to 64 bits on 32 bits architecture. This change may have caused an error when building test cases on hppa and PowerPC platforms: 

https://buildd.debian.org/status/fetch.php?pkg=libical3&arch=hppa&ver=3.0.19-1&stamp=1735155399&raw=0

```
62: Test command: /usr/bin/python3 "-I" "/build/reproducible-path/libical3-3.0.19/src/test/libical-glib/recurrence.py"
62: Working Directory: /build/reproducible-path/libical3-3.0.19/obj-hppa-linux-gnu/bin
62: Environment variables:
62:  GI_TYPELIB_PATH=/build/reproducible-path/libical3-3.0.19/obj-hppa-linux-gnu/src/libical-glib
62:  ZONEINFO_DIRECTORY=/build/reproducible-path/libical3-3.0.19/zoneinfo
62:  LD_LIBRARY_PATH=/build/reproducible-path/libical3-3.0.19/obj-hppa-linux-gnu/lib
62: Test timeout computed to be: 10000000
62: Traceback (most recent call last):
62:   File "/build/reproducible-path/libical3-3.0.19/src/test/libical-glib/recurrence.py", line 239, in <module>
62:     assert(result[i] == start + i*secs_per_day)
62:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
62: AssertionError
62/64 Test #62: libical-glib-recurrence ..............***Failed    1.07 sec
Traceback (most recent call last):
  File "/build/reproducible-path/libical3-3.0.19/src/test/libical-glib/recurrence.py", line 239, in <module>
    assert(result[i] == start + i*secs_per_day)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

According to the original issue author

> I think the problem is in src/Net-ICal-Libical/netical.i:
> In this define, "start" and "array" should be "unsigned long long" or "uint64_t":
int icalrecur_expand_recurrence(const char* rule, int start,
                                int count, int *array);
> Note that int or long can be 64-bit on 64-bit platforms, but on 32-bit platforms you need
> to use "long long" or "uint64_t" to refer to a 64-bit (time_t) value.

But since neither he or I are python experts, we wouldn't know how to fix properly this issue. 

Do you have an idea? 

Thanks on advance

**Comment by winterz** [comment]
I believe this is due to the hard coded time_t type in the i_cal_recur_expand_recurrence section of src/libical-glib/api/i-cal-recur.xml

Maybe about glib gurus @mcrha or @tintou have some ideas

this should be fixed anyway as we would need to support __time64_t types on some systems

**Comment by mcrha** [comment]
> Debian switched the time_t length to 64 bits on 32 bits architecture. 

Being it so, using `time_t` type should be safe, because it represents the right type and size whichever platform and setting the distro uses. I'd guess so at least.

Nonetheless, looking into the generated `ICalGLib-3.0.gir`, the `i_cal_recur_expand_recurrence` is declared as having `return-value` as an array of `glong`, which might be the reason of the problem.

Does the below change (which changes `element-type long` to `element-type time_t`) help, please?

```diff
diff --git a/src/libical-glib/api/i-cal-recur.xml b/src/libical-glib/api/i-cal-recur.xml
index 870ea61b..d7ae95b1 100644
--- a/src/libical-glib/api/i-cal-recur.xml
+++ b/src/libical-glib/api/i-cal-recur.xml
@@ -18,7 +18,7 @@
         <parameter type="const gchar *" name="rule" comment="The rule of the recurrence"/>
         <parameter type="time_t" name="start" comment="The start seconds past the POSIX epoch"/>
         <parameter type="gint" name="count" comment="The number of elements to be filled up in the @array"/>
-        <returns type="GArray *" annotation="array, element-type long, transfer full" comment="If successful, return the array. NULL if failed."/>
+        <returns type="GArray *" annotation="array, element-type time_t, transfer full" comment="If successful, return the array. NULL if failed."/>
         <comment xml:space="preserve">Fills an array with the 'count' number of occurrences generated by the rrule. Note that the times are returned in UTC, but the times are calculated in local time. YOu will have to convert the results back into local time before using them.</comment>
         <custom>        time_t *array;
         GArray *garray;
```

The array is constructed with the `time_t` element type, it's the GObject introspection mistyping its content due to the annotation. This change would need more testing.

**Comment by babelouest** [comment]
Hello, 

The patch seems to fix the build for both architectures that failed recently: 
https://buildd.debian.org/status/fetch.php?pkg=libical3&arch=hppa&ver=3.0.19-2&stamp=1736255662&raw=0
https://buildd.debian.org/status/fetch.php?pkg=libical3&arch=powerpc&ver=3.0.19-2&stamp=1736198642&raw=0

Other architectures are fine too.

Thanks a lot! I'll upload the new package soon. 

Will this patch be applied upstream as well?

**Comment by hdeller** [comment]
Thanks for finding and fixing this bug!

**Comment by babelouest** [comment]
The fix has been applied in the package [3.0.19-3](https://tracker.debian.org/news/1603081/accepted-libical3-3019-3-source-into-unstable/) in Debian unstable. I'm closing this issue then, thanks!

**Comment by mcrha** [comment]
This should be closed by an upstream change, by applying the snippet from [the above comment ](https://github.com/libical/libical/issues/852#issuecomment-2573344735) into the sources. I cannot reopen this, but I suggest you reopen it.

**Comment by babelouest** [comment]
@winterz , should we close this issue now that the code is applied in the main branch?

**Comment by winterz** [comment]
yes indeed.
thanks for the reminder
